"""Frame-by-frame renderer for scuti-intro.html (same idea as HyperFrames: HTML + GSAP -> MP4).

Usage:
  python render_frames.py --stills 0.8,2.6,5.0,8.5,12.8,15.2,18.0   # quick still check -> animation/stills/
  python render_frames.py                                          # full render -> video/scuti-ai-motion-graphics.mp4

How it works: the GSAP master timeline is paused; for every frame we call seekTo(t) and take a screenshot,
so the output is perfectly smooth (no dropped frames like real-time screen recording).
"""
import argparse, os, shutil, subprocess, sys, time
from pathlib import Path
import imageio_ffmpeg
from playwright.sync_api import sync_playwright

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
FPS = 30
FF = imageio_ffmpeg.get_ffmpeg_exe()
URL = (HERE / "scuti-intro.html").as_uri() + "?render=1"


def open_page(p):
    b = p.chromium.launch(channel="chrome", headless=False, args=["--window-size=1940,1140"])
    pg = b.new_page(viewport={"width": 1920, "height": 1080}, device_scale_factor=1)
    pg.goto(URL, wait_until="networkidle")
    pg.wait_for_function("window.renderReady === true", timeout=30000)
    return b, pg


def stills(times):
    out = HERE / "stills"; out.mkdir(exist_ok=True)
    with sync_playwright() as p:
        b, pg = open_page(p)
        for t in times:
            pg.evaluate(f"seekTo({t})")
            pg.screenshot(path=str(out / f"still-{t:05.2f}s.png"))
            print("still", t)
        b.close()


def make_audio(dur, path):
    """Calm ambient pad (A-minor-ish chord with slow tremolo) generated by ffmpeg - no external music."""
    expr = ("0.10*sin(2*PI*220*t)*(0.6+0.4*sin(2*PI*0.25*t))"
            "+0.07*sin(2*PI*261.63*t)*(0.6+0.4*sin(2*PI*0.31*t))"
            "+0.07*sin(2*PI*329.63*t)*(0.6+0.4*sin(2*PI*0.21*t))"
            "+0.05*sin(2*PI*110*t)")
    subprocess.run([FF, "-y", "-f", "lavfi", "-i", f"aevalsrc='{expr}':s=48000:d={dur}",
                    "-af", f"lowpass=f=1800,afade=t=in:d=1.5,afade=t=out:st={dur-1.8}:d=1.8,volume=0.8",
                    "-c:a", "aac", "-b:a", "160k", str(path)], check=True, capture_output=True)


def full():
    frames = HERE / "frames"
    if frames.exists(): shutil.rmtree(frames)
    frames.mkdir()
    log = []
    t0 = time.time()
    with sync_playwright() as p:
        b, pg = open_page(p)
        dur = pg.evaluate("window.__duration")
        n = int(round(dur * FPS))
        for f in range(n):
            pg.evaluate(f"seekTo({f / FPS})")
            pg.screenshot(path=str(frames / f"f{f:05d}.jpg"), type="jpeg", quality=92)
            if f % 15 == 0:
                msg = f"frame {f:4d}/{n}  t={f / FPS:5.2f}s  elapsed={time.time() - t0:5.1f}s"
                print(msg, flush=True)
                if f % 60 == 0: log.append(msg)
        b.close()
    vid_dir = ROOT / "video"; vid_dir.mkdir(exist_ok=True)
    silent = HERE / "_silent.mp4"; audio = HERE / "_pad.m4a"; out = vid_dir / "scuti-ai-motion-graphics.mp4"
    subprocess.run([FF, "-y", "-framerate", str(FPS), "-i", str(frames / "f%05d.jpg"),
                    "-vf", "scale=in_range=pc:out_range=tv,format=yuv420p", "-c:v", "libx264", "-pix_fmt", "yuv420p", "-crf", "18", "-preset", "medium", str(silent)],
                   check=True, capture_output=True)
    make_audio(dur, audio)
    subprocess.run([FF, "-y", "-i", str(silent), "-i", str(audio), "-c:v", "copy", "-c:a", "copy", "-shortest",
                    "-movflags", "+faststart", str(out)], check=True, capture_output=True)
    # contact sheet for the critic (1 frame per second, 5x4 grid)
    subprocess.run([FF, "-y", "-i", str(out), "-vf", "fps=1,scale=480:-1,tile=5x4", "-frames:v", "1",
                    str(HERE / "contact-sheet.png")], check=True, capture_output=True)
    silent.unlink(); audio.unlink(); shutil.rmtree(frames)
    msg = f"DONE {n} frames @ {FPS}fps -> {out.name} in {time.time() - t0:.1f}s"
    print(msg); log.append(msg)
    (HERE / "render-log.txt").write_text("\n".join(log), encoding="utf-8")


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--stills")
    a = ap.parse_args()
    if a.stills:
        stills([float(x) for x in a.stills.split(",")])
    else:
        full()
