"""Step 1 of the pipeline: narration text -> voice (edge-tts) + timing data for lip-sync.

Outputs (in ../assets):
  narration-vi.mp3      synthesized voice (vi-VN-NamMinhNeural)
  boundaries.json       word + sentence boundaries returned by edge-tts (seconds)
  timeline.js           window.TIMELINE = {duration, sentences, words, env}  (env = mouth-open envelope @ 50 fps)
  waveform.png          waveform picture (ffmpeg showwavespic) for documentation

Usage:  python make_tts.py [--voice vi-VN-NamMinhNeural] [--rate +4%] [--pitch +18Hz]
"""
import argparse, asyncio, json, math, os, subprocess, sys, array

import edge_tts
import imageio_ffmpeg

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
ASSETS = os.path.join(ROOT, "assets")
FFMPEG = imageio_ffmpeg.get_ffmpeg_exe()
TICK = 10_000_000  # edge-tts offsets are in 100-ns ticks


async def synth(text, voice, rate, pitch, boundary, mp3_path):
    com = edge_tts.Communicate(text, voice, rate=rate, pitch=pitch, boundary=boundary)
    marks = []
    with open(mp3_path, "wb") as f:
        async for chunk in com.stream():
            if chunk["type"] == "audio":
                f.write(chunk["data"])
            elif chunk["type"] in ("WordBoundary", "SentenceBoundary"):
                marks.append({
                    "text": chunk["text"],
                    "start": round(chunk["offset"] / TICK, 3),
                    "end": round((chunk["offset"] + chunk["duration"]) / TICK, 3),
                })
    return marks


def envelope(mp3_path, fps=50):
    """Decode mp3 -> 16 kHz mono PCM, return RMS per 1/fps second normalised to 0..1."""
    raw = subprocess.run([FFMPEG, "-v", "error", "-i", mp3_path, "-ac", "1", "-ar", "16000",
                          "-f", "s16le", "-"], capture_output=True, check=True).stdout
    pcm = array.array("h"); pcm.frombytes(raw)
    hop = 16000 // fps
    vals = []
    for i in range(0, len(pcm), hop):
        seg = pcm[i:i + hop]
        vals.append(math.sqrt(sum(s * s for s in seg) / max(1, len(seg))))
    peak = sorted(vals)[int(len(vals) * 0.98)] or 1
    env = [min(1.0, v / peak) for v in vals]
    # light smoothing (attack fast, release slower) so the mouth does not flicker
    out, cur = [], 0.0
    for v in env:
        cur = v if v > cur else cur * 0.6 + v * 0.4
        out.append(round(cur, 3))
    return out, len(pcm) / 16000


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--voice", default="vi-VN-NamMinhNeural")
    ap.add_argument("--rate", default="+4%")
    ap.add_argument("--pitch", default="+18Hz")
    ap.add_argument("--text", default=os.path.join(HERE, "narration-vi.txt"))
    a = ap.parse_args()
    os.makedirs(ASSETS, exist_ok=True)
    text = open(a.text, encoding="utf-8").read().strip()
    mp3 = os.path.join(ASSETS, "narration-vi.mp3")
    tmp = os.path.join(ASSETS, "_sentence-pass.mp3")

    print(f"[edge-tts] voice={a.voice} rate={a.rate} pitch={a.pitch}")
    words = asyncio.run(synth(text, a.voice, a.rate, a.pitch, "WordBoundary", mp3))
    sentences = asyncio.run(synth(text, a.voice, a.rate, a.pitch, "SentenceBoundary", tmp))
    os.remove(tmp)
    env, dur = envelope(mp3)
    print(f"[edge-tts] audio  -> {os.path.relpath(mp3, ROOT)}  ({dur:.2f} s)")
    print(f"[edge-tts] {len(words)} word boundaries, {len(sentences)} sentence boundaries")
    for s in sentences:
        print(f"   {s['start']:6.2f}s -> {s['end']:6.2f}s  {s['text'][:70]}")

    json.dump({"voice": a.voice, "rate": a.rate, "pitch": a.pitch, "duration": round(dur, 3),
               "sentences": sentences, "words": words},
              open(os.path.join(ASSETS, "boundaries.json"), "w", encoding="utf-8"), ensure_ascii=False, indent=1)
    tl = {"duration": round(dur, 3), "fps": 50, "sentences": sentences, "words": words, "env": env}
    with open(os.path.join(ASSETS, "timeline.js"), "w", encoding="utf-8") as f:
        f.write("// generated by scripts/make_tts.py - do not edit by hand\n")
        f.write("window.TIMELINE = " + json.dumps(tl, ensure_ascii=False) + ";\n")
    print(f"[timeline] assets/timeline.js  env frames={len(env)} @50fps")

    subprocess.run([FFMPEG, "-v", "error", "-y", "-i", mp3, "-filter_complex",
                    "showwavespic=s=1200x200:colors=#d32f2f", "-frames:v", "1",
                    os.path.join(ASSETS, "waveform.png")], check=True)
    print("[ffmpeg] assets/waveform.png")


if __name__ == "__main__":
    main()
